// <auto-generated />
namespace ProduceManager.Form.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_delete_and_code : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_delete_and_code));
        
        string IMigrationMetadata.Id
        {
            get { return "201804011542413_add_delete_and_code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
