// <auto-generated />
namespace ProduceManager.Forms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addsalebill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsalebill));
        
        string IMigrationMetadata.Id
        {
            get { return "201804151330287_add-sale-bill"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
