// <auto-generated />
namespace ProduceManager.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newrecordentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newrecordentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201804181619444_new-record-entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
